def get_styled_html(content: str) -> str:
    return f"""
    <html>
    <head>
        <meta charset="UTF-8">

        <style>
            body {{
                font-family: 'Segoe UI', sans-serif;
                padding: 20px;
                background: #f4f6f9;
                color: #333;
            }}

            /* HEADER */
            h1 {{
                color: #1e293b;
                border-bottom: 4px solid #4CAF50;
                padding-bottom: 8px;
                font-size: 26px;
                margin-bottom: 15px;
            }}

            h2 {{
                color: #334155;
                margin-top: 20px;
                font-size: 18px;
            }}

            hr {{
                margin: 10px 0;
                border: none;
                border-top: 1px solid #ddd;
            }}

            /* CARD STYLE */
            .section {{
                background: white;
                padding: 15px;
                border-radius: 10px;
                box-shadow: 0 4px 10px rgba(0,0,0,0.08);
                margin-bottom: 15px;
                page-break-inside: avoid;
            }}

            /* KPI BOXES */
            .kpi-container {{
                display: flex;
                gap: 10px;
                margin-bottom: 10px;
            }}

            .kpi {{
                flex: 1;
                background: linear-gradient(135deg, #4CAF50, #2e7d32);
                color: white;
                padding: 10px;
                border-radius: 8px;
                text-align: center;
                font-size: 14px;
            }}

            .kpi h3 {{
                margin: 0;
                font-size: 16px;
            }}

            .kpi span {{
                font-size: 12px;
                opacity: 0.8;
            }}

            /* TABLE */
            table {{
                width: 100%;
                border-collapse: collapse;
                margin-top: 8px;
                margin-bottom: 15px;
                background: white;
                border-radius: 8px;
                overflow: hidden;
                page-break-inside: avoid;
            }}

            th {{
                background: #4CAF50;
                color: white;
                padding: 8px;
                text-align: left;
            }}

            td {{
                padding: 8px;
                border-bottom: 1px solid #eee;
            }}

            tr:nth-child(even) {{
                background-color: #f9f9f9;
            }}

            /* CHARTS */
            img {{
                display: block;
                margin: 15px auto;
                max-width: 90%;
                border-radius: 8px;
                box-shadow: 0 3px 6px rgba(0,0,0,0.1);
                page-break-inside: avoid;
            }}

            /* STATUS COLORS */
            .good {{
                color: #2e7d32;
                font-weight: bold;
            }}

            .bad {{
                color: #c62828;
                font-weight: bold;
            }}

            /* FOOTER */
            footer {{
                text-align: center;
                margin-top: 15px;
                font-size: 12px;
                color: #888;
            }}

            @page {{
                size: A4;
                margin: 10mm;
            }}
        </style>
    </head>

    <body>

        <div class="section">
            {content}
        </div>

        <footer>
            Generated by AI Finance Assistant 🚀
        </footer>

    </body>
    </html>
    """