from __future__ import annotations
from pathlib import Path
from typing import Any
import json

def _markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "_No data available._"

    header_line = "| " + " | ".join(headers) + " |"
    separator = "| " + " | ".join(["---"] * len(headers)) + " |"
    body = "\n".join("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join([header_line, separator, body])

def _money(value: Any) -> str:
    try:
        return f"{float(value):,.2f}"
    except Exception:
        return "0.00"

def build_report_markdown(state):
    summary = state.get("expense_summary", {}) or {}
    budget = state.get("budget_analysis", {}) or {}
    savings = state.get("savings_context", {}) or {}

    income = float(state.get("monthly_income", 0))
    total = round(sum(summary.values()), 2)
    balance = round(income - total, 2)

    # ✅ FIXED
    forecast = state.get("forecast", 0)
    bar_chart = state.get("bar_chart", "")
    pie_chart = state.get("pie_chart", "")

    bar_chart = f"../{Path(bar_chart).as_posix()}" if bar_chart else ""
    pie_chart = f"../{Path(pie_chart).as_posix()}" if pie_chart else ""

    if not summary or all(v == 0 for v in summary.values()):
        top = "none"
    else:
        top = max(summary, key=summary.get)

    expense_rows = [[k.capitalize(), _money(v)] for k, v in summary.items()]
    budget_rows = [
        [k.capitalize(), v.get("status", "-"), _money(v.get("difference", 0))]
        for k, v in budget.items()
    ]

    savings_target = savings.get("plan", {}).get("target", 0)

    forecast_note = ""
    transactions = state.get("transactions", [])
    avg_spending = total/ len(transactions) if transactions else 0

    if forecast <= 0:
        forecast_note =  "ℹ️ Not enough data to predict future spending."
    elif forecast > avg_spending:
        forecast_note = "⚠️ Spending trend is increasing. You may overspend next month."
    elif forecast < avg_spending:
        forecast_note = "✅ Spending trend is decreasing. Good financial control."
    else:
        forecast_note = "ℹ️ Spending trend is stable."


    return f"""# 💰 AI Finance Monthly Report

---

## 📊 Overview
- **Monthly Income:** {_money(income)}
- **Total Expenses:** {_money(total)}
- **Remaining Balance:** {_money(balance)}
- **Top Category:** {top.capitalize()}

---

## 🍔 Expense Breakdown

{_markdown_table(["Category", "Amount"], expense_rows)}

---

## ⚠️ Budget Analysis

{_markdown_table(["Category", "Status", "Difference"], budget_rows)}

---

## 💡 Savings Plan
- **Recommended Target:** {_money(savings_target)}

---

## 📈 Forecast
- **Predicted Next Spending:** {_money(forecast)}

---

## 📊 Charts

![Bar Chart]({bar_chart})
![Pie Chart]({pie_chart})

---

## 📈 Insight
You are {"overspending ⚠️" if balance < 0 else "managing well ✅"}.

{forecast_note}

---

✨ Generated by AI Finance Assistant
"""

def write_report(output_path: str, content: str) -> str:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return str(path)

def write_trace_log(trace_path: str, trace_data: list[dict[str, Any]]) -> str:
    path = Path(trace_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(trace_data, indent=2), encoding="utf-8")
    return str(path)